= Caps n' T-shirts Web

== Description

Welcome to the Caps & T-Shirts Web Application!

Here you can create, update, delete and buy products available in the platform.

You will also receive a *Console Email* with all the details of your order.

== Running the Application

* Make sure you have Docker installed in your OS

* Build the Docker Container with the following command:

IMPORTANT: If you are using Linux include *_sudo_* before this command
[source] 
docker build -t napptilus_iati .

* Run the Docker container in port 8000:

IMPORTANT: If you are using Linux include *_sudo_* before this command
[source]
docker run -p 8000:8000 napptilus_iati

* Application will be available as: *_localhost:8000_*


== API Documentation

=== 1. Product List Ordered by Creation Date, First Caps, Then T-Shirts
GET request to endpoint: http://localhost:8000/products

=== 2. Create Product
* Gorra: POST request to endpoint: http://localhost:8000/products/create/gorra

* Camiseta: POST request to endpoint: http://localhost:8000/products/create/camiseta

=== 3. Update Product
* Gorra: PUT request to endpoint: http://localhost:8000/products/update/gorra/#{product_id}#

* Camiseta: PUT request to endpoint: http://localhost:8000/products/update/camiseta/#{product_id}#


=== 4. Delete Product (Logical)
* Gorra: DELETE request to endpoint: http://localhost:8000/products/delete/gorra/#{product_id}#

* Camiseta: DELETE request to endpoint: http://localhost:8000/products/delete/camiseta/#{product_id}#

NOTE: Check media/gifs to see some gifs using the API

== 5. Other Back-end Features
* Everytime the Docker container is run, the database is restored to the initial conditions (no orders, just initial default stock) before the web server is started

* There is a crontab job that checks and updates (if necessary) the current stock of every product

